name: Run Trading Bot
on:
  schedule:
    - cron: '0 */6 * * *' # سيعيد تشغيل نفسه كل 6 ساعات لضمان الاستمرارية
  workflow_dispatch: # يسمح لك بتشغيله يدوياً

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: set-up-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install ccxt openai
      - name: Run Bot
        run: python main.py
